version: "3.0"
services:
  web:
    volumes:
      - ./:/app/local/teko/
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    ports:
      - "4567:4567"
    links:
      - mysql
      - memcached
      - redis
      - redis_ml
      - redis_materiall
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - 3306:3306
    networks:
      - backend
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: "redis-server --requirepass teko123"
  redis_ml:
    image: redis:latest
    command: "redis-server --requirepass teko123"
  redis_materiall:
    image: redis:latest
    command: "redis-server --requirepass teko123"
