-- MySQL Script generated by MySQL Workbench
-- Tue Aug  1 15:51:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema trendu_development
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trendu_development
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teko_development` DEFAULT CHARACTER SET latin1 ;
USE `teko_development` ;

-- -----------------------------------------------------
-- Table `trendu_development`.`teko_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teko_development`.`teko_payment` (
  `id` INT(10) UNSIGNED NOT NULL,
  `mangopay_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `heidelpay_id` VARCHAR(32) NULL DEFAULT NULL,
  `type` ENUM('cash_in','cash_out') NULL DEFAULT NULL,
  `method_type` ENUM('paypal') NULL DEFAULT NULL,
  `provider` ENUM('visa','mastercard','amex') NULL DEFAULT NULL,
  `card_identifier` VARCHAR(16) NULL DEFAULT NULL,
  `iban` VARCHAR(50) NULL DEFAULT NULL,
  `bic` VARCHAR(50) NULL DEFAULT NULL,
  `card_owner_information` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`entity_id`),
  UNIQUE INDEX `heidelpay_id` (`heidelpay_id` ASC),
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
